version: '2'
services:
  haasbot:
    build:
      context: .
#      args:
#        user: haasbot
    container_name: haasbot
    ports:
      - "8090:8090"
      - "8092:8092"
      - "2222:22"
    volumes:
      - "/home/haasbot/HTS:/root/HTS"
      - "/etc/localtime:/etc/localtime:ro"
